# Generated by Django 4.2.3 on 2023-08-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_list_item_options_alter_list_item_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_item',
            old_name='item',
            new_name='name',
        ),
        migrations.AddField(
            model_name='list_item',
            name='added_to_cart',
            field=models.BooleanField(default=False),
        ),
    ]
