# Generated by Django 4.2.3 on 2023-08-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_item_list_item_name_list_item_added_to_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
